export async function runErrorHandlers(error: Error): Promise<void> {
  console.error("error out!!", error);
}
